id: A04CD9ABA
title: 'The Swift Fulfilment of Wishes: A Prayer of Aspiration'
type: translation
pechas:
- I1667318B
- I3CC10D70
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:07:47.117055
  last_modified_at: 2023-01-04 12:07:47.117072
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I1667318B/F122: 0E9D
  I3CC10D70/C153: 0E9D
